#!/usr/bin/env bash
set -eu

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. "$DIR/common-setup.sh"

TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'cache')
trap "rm -rf \"$TMPDIR\"" EXIT

(
    cd "$DIR"

    for x in nixpkgs reflex reflex-dom reflex-todomvc ; do
	nix-push --dest "$TMPDIR" --key-file ~/.reflex-platform/ryantrinkle.com-1 "$(nix-instantiate $NIXOPTS -j 8 --add-root "$DIR/gc-roots/cache-nixpkgs.drv" --indirect -E "(import <nixpkgs> {}).fetchgit (import ./$x/git.nix)")"
    done
    for x in $(eval "echo $(nix-instantiate $NIXOPTS --eval --read-write-mode -E 'let this = (import ./. {}); in this.nixpkgs.stdenv.lib.concatStringsSep " " this.cacheTargetSystems')") ; do
        nix-push --dest "$TMPDIR" --key-file ~/.reflex-platform/ryantrinkle.com-1 "$(nix-instantiate $NIXOPTS -j 8 --add-root "$DIR/gc-roots/cache-$x.drv" --indirect -E "import ./shell.nix { system = \"$x\"; }")"
    done

    nix-shell $NIXOPTS -p s3cmd --run "s3cmd sync '$TMPDIR/' s3://nixcache.reflex-frp.org/"
)
