#! /bin/bash

if [[ $# -eq 0 ]]
  then echo "Usage: $0 <packagename> [<packagename...>]"
       echo "Uses xdg-open to open the documentation for given (Haskell) packages"
       echo "from the nix-store. For example, try"
       echo " $0 reflex reflex-dom-core jsaddle jsaddle-dom lens"
  else export DOCSFOR_PKGLIST="$@"
       function openTheDocs () {
          echo $DOCSFOR_PKGLIST | xargs -d' ' -n1 --replace ghc-pkg field {} haddock-html | sed 's#.*: \(.*\)#\1/index.html#' | xargs -n1 xdg-open
       }
       export -f openTheDocs
       ./try-reflex --command "openTheDocs"
  fi
