#!/usr/bin/env bash
set -eu

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. "$DIR/common-setup.sh"

REPO="$1"

DIFF="$(git -C "$REPO/.." diff --cached -- "$REPO/git.json")"
DIFF_ERR=$?

if [ "$DIFF_ERR" -ne 0 ] ; then
    >&2 echo "Error: could not determine whether $REPO/git.json already has pending modifications"
    exit 1
elif [ -n "$DIFF" ] ; then
    >&2 echo -n "$DIFF"
    >&2 echo "Error: $REPO/git.json has pending modifications"
    exit 1
fi

diff -u --label "a/$REPO/git.json" --label "b/$REPO/git.json" <(git -C "$REPO/.." show "HEAD:$REPO/git.json") <(git_manifest "$REPO") | git apply --cached
