#!/usr/bin/env bash
set -eu
set -o pipefail

readonly DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$DIR/common-setup.sh"

REPO="$1"

checkStatus() {
    local diff=$(git -C "$REPO/.." diff --cached -- "$REPO/git.nix")
    local diff_exit=$?

    if [[ "$diff_exit" -ne 0 ]]; then
        >&2 echo "Error: could not determine whether $REPO/git.nix already has pending modifications"
        exit 1
    elif [[ -n "$diff" ]]; then
        >&2 echo -n "$diff"
        >&2 echo "Error: $REPO/git.nix has pending modifications"
        exit 1
    fi
}

applyPatch() {
    diff -u --label "a/$REPO/git.nix" --label "b/$REPO/git.nix" \
         <(git -C "$REPO/.." show "HEAD:$REPO/git.nix") \
         <(git_manifest "$REPO") \
        | git apply --cached
}

main() {
    checkStatus
    applyPatch
}

main "$@"
