#!/usr/bin/env bash
set -eu
set -o pipefail

DIR="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source "$DIR/common-setup.sh"

# This crazy workaround ensures that it will work on both Mac OS and
# Linux; see
# https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
CLEAN=$(mktemp -d 2>/dev/null || mktemp -d -t 'clean')
DIFF=$(mktemp 2>/dev/null || mktemp -t 'diff')

trap "rm \"$DIFF\" ; rm -rf \"$CLEAN\"" EXIT

cloneRepo() {
    git clone -n "$DIR" "$CLEAN"
}

checkoutHEAD() {
    git -C "$CLEAN" checkout "$(git -C "$DIR" rev-parse HEAD)"
}

saveDiff() {
    git -C "$DIR" diff --cached > "$DIFF"
}

applyDiff() {
    if [[ -s "$DIFF" ]]; then
        git -C "$CLEAN" apply --index < "$DIFF"
    fi
}

runTests() {
    cd $CLEAN
    nice ./test "$@"
}

main() {
    cloneRepo
    checkoutHEAD
    saveDiff
    applyDiff
    runTests "$@"
}

main "$@"
