#!/usr/bin/env bash
set -eu

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. "$DIR/common-setup.sh"

(
CLEAN=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir') # This crazy workaround ensures that it will work on both Mac OS and Linux; see https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
trap "rm -rf \"$CLEAN\"" EXIT

git clone -n "$DIR" "$CLEAN"
git -C "$CLEAN" checkout "$(git -C "$DIR" rev-parse HEAD)"
git -C "$DIR" diff --cached | git -C "$CLEAN" apply --index

cd $CLEAN

nice ./test
)
