#!/usr/bin/env bash
set -eu
set -o pipefail

readonly DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$DIR/common-setup.sh"

runShell() {
    local expr="{path}: let this = import path {}; in this.nixpkgs.runCommand \"shell\" { buildInputs = [ (this.ghc.ghcWithPackages (pkg: with pkg; [ shelly hspec ])) ]; } \"\""

    nix-shell $NIXOPTS \
              -E "$expr" --argstr path "$DIR/." --show-trace \
              --command "runghc $(printf "%q " "$DIR/test.hs" "$@") ; exit $?"
}

main() {
    runShell "$@"
}

main "$@"
