#!/usr/bin/env bash
set -eu

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. "$DIR/common-setup.sh"

if [ "$#" -lt 2 ] ; then
  echo "Usage: $0 PLATFORM PACKAGE ..."
  echo "  PLATFORM can be either \"ghc\" or \"ghcjs\""
  echo "  PACKAGE can be any cabal package name"
  echo "  Any extra arguments will be passed along to nix-shell"
  echo
  echo "This script will drop you into a nix shell with access to the prerequisites of the chosen package on the chosen platform.  From there, you should be able to cabal configure [--ghcjs], cabal build, and cabal test.  Note that cabal install will not interoperate with Nix packages, and may not work at all."
fi

PLATFORM="$1"
shift
PACKAGE="$1"
shift

nix-shell $NIXOPTS -I "$DIR" -E "let this = import ./. {}; in with (this.$PLATFORM); with (import <nixpkgs/pkgs/development/haskell-modules/lib.nix> { pkgs = import <nixpkgs> {}; }); (overrideCabal $PACKAGE (drv: { buildDepends = drv.buildDepends ++ [ this.ghc.cabal-install ]; })).env" -j 8 "$@"
