{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "network-byte-order"; version = "0.1.6"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "kazu@iij.ad.jp";
      author = "Kazu Yamamoto";
      homepage = "";
      url = "";
      synopsis = "Network byte order utilities";
      description = "Peek and poke functions for network byte order.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          ];
        buildable = true;
        };
      tests = {
        "doctest" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
            (hsPkgs."doctest" or (errorHandler.buildDepError "doctest"))
            ];
          buildable = true;
          };
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/network-byte-order-0.1.6.tar.gz";
      sha256 = "f2b0ccc9b759d686af30aac874fc394c13c1fc8a3db00fac401c9339c263dc5e";
      });
    }) // {
    package-description-override = "-- Initial network-byte-order.cabal generated by cabal init.  For further\n-- documentation, see http://haskell.org/cabal/users-guide/\n\nname:                network-byte-order\nversion:             0.1.6\nx-revision: 1\nsynopsis:            Network byte order utilities\ndescription:         Peek and poke functions for network byte order.\nlicense:             BSD3\nlicense-file:        LICENSE\nauthor:              Kazu Yamamoto\nmaintainer:          kazu@iij.ad.jp\n-- copyright:\ncategory:            Network\nbuild-type:          Simple\n-- extra-source-files:  ChangeLog.md\ncabal-version:       >= 1.10\n\nlibrary\n  ghc-options:         -Wall\n  exposed-modules:     Network.ByteOrder\n  -- other-modules:\n  -- other-extensions:\n  build-depends:       base >= 4.9 && < 5\n                     , bytestring\n  -- hs-source-dirs:\n  default-language:    Haskell2010\n  if impl(ghc >= 8)\n      default-extensions:  Strict StrictData\n\ntest-suite doctest\n  type:                 exitcode-stdio-1.0\n  default-language:     Haskell2010\n  hs-source-dirs:       test\n  ghc-options:          -Wall\n  main-is:              doctests.hs\n  build-depends:        base\n                      , bytestring\n                      , doctest\n\nsource-repository head\n  type:     git\n  location: git://github.com/kazu-yamamoto/network-byte-order.git\n";
    }