#!/usr/bin/env bash
set -euo pipefail

name="${1##*/}"
name="${name%.app}"

uuid="$(xcrun simctl create "$name" com.apple.CoreSimulator.SimDeviceType.iPhone-7 com.apple.CoreSimulator.SimRuntime.iOS-12-4)"

function cleanup {
  if [ -n "$uuid" ]; then
    echo "Cleaning up simulator" >&2
    xcrun simctl shutdown "$uuid" 2>/dev/null
    xcrun simctl delete "$uuid"
  fi
}
trap cleanup EXIT

echo Opening Simulator... >&2
open -a Simulator --args -CurrentDeviceUDID "$uuid"
sleep 5

echo Installing "$name".app >&2
xcrun simctl install "$uuid" "$1"

echo Launching "$name" >&2
xcrun simctl launch --console "$uuid" "$name"
